"""
System Design Interview Question Bank

35 questions across 7 topics:
1. Load Balancing & Scaling
2. Caching Strategies
3. Database Design & Sharding
4. Message Queues & Event-Driven Architecture
5. Microservices & API Design
6. CAP Theorem & Distributed Systems
7. Performance & Reliability
"""

QUESTIONS = [
    # =====================================================================
    # TOPIC 1: Load Balancing & Scaling
    # =====================================================================
    {
        "id": "lb_001",
        "topic": "Load Balancing & Scaling",
        "difficulty": "easy",
        "type": "mcq",
        "question": "What algorithm does a round-robin load balancer use to distribute requests?",
        "options": [
            "Send each request to the server with the fewest active connections",
            "Distribute requests sequentially across the server pool, cycling back to the start",
            "Route requests based on the client's geographic location",
            "Randomly select a server for each incoming request",
        ],
        "correct": 1,
        "explanation": "Round-robin distributes requests in sequential order across the available servers. When the end of the pool is reached, it cycles back to the first server. It's simple and works well when servers have similar capacity, but doesn't account for varying server loads.",
        "hint": "Think about the name — what does 'round-robin' mean in a tournament or scheduling context?",
    },
    {
        "id": "lb_002",
        "topic": "Load Balancing & Scaling",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What is the main limitation of a single load balancer in a production system?",
        "options": [
            "It cannot terminate TLS connections",
            "It becomes a single point of failure",
            "It only supports HTTP traffic",
            "It cannot perform health checks",
        ],
        "correct": 1,
        "explanation": "A single load balancer is a single point of failure (SPOF). If it goes down, all traffic to the backend servers is lost. Production deployments typically use a pair of load balancers in active-passive or active-active mode, often with a floating IP or DNS failover.",
        "hint": "What happens when that one device fails? Is there a backup?",
    },
    {
        "id": "lb_003",
        "topic": "Load Balancing & Scaling",
        "difficulty": "medium",
        "type": "mcq",
        "question": "Which load-balancing algorithm is most appropriate when backend servers have different processing capacities?",
        "options": [
            "Round-robin",
            "Weighted round-robin",
            "Random selection",
            "IP hash",
        ],
        "correct": 1,
        "explanation": "Weighted round-robin assigns a weight to each server proportional to its capacity. A server with weight 3 gets three times as many requests as one with weight 1. This handles heterogeneous server pools well, unlike plain round-robin which treats all servers equally.",
        "hint": "Not all servers are created equal — what if one is twice as powerful as the others?",
    },
    {
        "id": "lb_004",
        "topic": "Load Balancing & Scaling",
        "difficulty": "hard",
        "type": "mcq",
        "question": "In a distributed system, what problem does 'connection draining' on a load balancer solve?",
        "options": [
            "Prevents database connection pool exhaustion",
            "Allows in-flight requests to complete before removing a backend server",
            "Reduces TLS handshake overhead by reusing connections",
            "Prioritizes WebSocket connections over HTTP",
        ],
        "correct": 1,
        "explanation": "Connection draining (or graceful shutdown) lets a load balancer stop sending new requests to a backend server being taken offline, while still allowing existing in-flight requests to complete. Without it, active requests would be abruptly terminated during deployments or scaling down.",
        "hint": "What happens to requests that are still being processed when you remove a server?",
    },
    {
        "id": "lb_005",
        "topic": "Load Balancing & Scaling",
        "difficulty": "easy",
        "type": "open_ended",
        "question": "Explain the difference between horizontal scaling and vertical scaling. When would you choose one over the other?",
        "correct": None,
        "explanation": "Vertical scaling (scaling up) means adding more power to an existing server — more CPU, RAM, or storage. It's simpler but has a hard upper limit and can be more expensive per unit of capacity. Horizontal scaling (scaling out) means adding more servers to the pool. It's virtually unlimited, provides better fault tolerance, and often uses commodity hardware, but introduces complexity in load balancing, data consistency, and inter-service communication. Choose vertical for: stateful services that are hard to distribute, quick capacity boosts, or small-scale needs. Choose horizontal for: large-scale systems, high availability requirements, or when cost efficiency at scale matters.",
        "hint": "One is like upgrading your car's engine; the other is like adding more cars to your fleet.",
    },

    # =====================================================================
    # TOPIC 2: Caching Strategies
    # =====================================================================
    {
        "id": "cache_001",
        "topic": "Caching Strategies",
        "difficulty": "easy",
        "type": "mcq",
        "question": "In the write-through caching strategy, what happens when data is written?",
        "options": [
            "Data is written only to the cache, and the database is updated asynchronously",
            "Data is written to both the cache and the database synchronously before acknowledging the write",
            "Data is written only to the database, and the cache is invalidated",
            "Data is written to the cache, which then lazily persists to the database",
        ],
        "correct": 1,
        "explanation": "Write-through writes to both cache and database synchronously. The write is only acknowledged after both stores confirm. This ensures cache-database consistency at the cost of higher write latency. It's good for read-heavy workloads where data consistency is critical.",
        "hint": "The 'through' part implies the write passes through the cache to reach the database.",
    },
    {
        "id": "cache_002",
        "topic": "Caching Strategies",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What problem does 'cache invalidation' primarily address?",
        "options": [
            "Preventing the cache from running out of memory",
            "Ensuring stale data in the cache is replaced when the source data changes",
            "Encrypting sensitive data before storing it in the cache",
            "Distributing cached data across multiple cache nodes",
        ],
        "correct": 1,
        "explanation": "Cache invalidation is the process of removing or updating cached data when the underlying source data changes. Without it, applications would serve stale data. It's famously one of the 'two hard things' in computer science because tracking all data dependencies and invalidation triggers is surprisingly complex.",
        "hint": "There are only two hard things in computer science... this is one of them.",
    },
    {
        "id": "cache_003",
        "topic": "Caching Strategies",
        "difficulty": "easy",
        "type": "mcq",
        "question": "Which cache eviction policy removes the item that was accessed least recently?",
        "options": [
            "First-In-First-Out (FIFO)",
            "Least Recently Used (LRU)",
            "Least Frequently Used (LFU)",
            "Time-To-Live (TTL)",
        ],
        "correct": 1,
        "explanation": "LRU evicts the item that hasn't been accessed for the longest time. It's based on the principle that data accessed recently is likely to be needed again soon (temporal locality). LRU is widely used in practice (e.g., Redis, CPU caches) and can be implemented efficiently with a doubly-linked list and a hash map.",
        "hint": "If you haven't needed it in a while, you probably won't need it soon — which strategy embodies this?",
    },
    {
        "id": "cache_004",
        "topic": "Caching Strategies",
        "difficulty": "hard",
        "type": "mcq",
        "question": "What is a 'cache stampede' (also called 'thundering herd') in the context of caching?",
        "options": [
            "A DDoS attack targeting the cache layer",
            "When a cached item expires and multiple concurrent requests all try to recompute it simultaneously, overwhelming the backend",
            "When the cache becomes full and starts evicting all items rapidly",
            "When cache replication lag causes inconsistent reads across regions",
        ],
        "correct": 1,
        "explanation": "A cache stampede occurs when a popular cached item expires and many requests arrive simultaneously. Each request finds a cache miss and tries to recompute the value, overwhelming the backend (database, computation, etc.). Solutions include: request coalescing (only one thread recomputes, others wait), early recomputation (refresh before expiry), and multi-level caching.",
        "hint": "Imagine a door that suddenly unlocks and everyone tries to rush through at once.",
    },
    {
        "id": "cache_005",
        "topic": "Caching Strategies",
        "difficulty": "medium",
        "type": "open_ended",
        "question": "You are designing a social media feed. Users follow thousands of accounts, and new posts are created constantly. Design a caching strategy that keeps feed reads fast while ensuring users see new posts within seconds.",
        "correct": None,
        "explanation": "A common approach is fanout-on-write (push model): when a user creates a post, pre-compute the feed for each follower by writing the post ID into a Redis sorted set per follower (scored by timestamp). Hot followers with millions of followers might use fanout-on-read (pull model) instead to avoid write amplification. Cache feed data in Redis with TTL (e.g., 24 hours). Use a separate cache for post content. Implement early recomputation for frequently accessed feeds (refresh when TTL is 70% expired). For consistency, use write-through for the feed cache and tolerate eventual consistency for cross-region reads.",
        "hint": "Should the system 'push' new posts to followers' caches or let followers 'pull' when they open the app?",
    },

    # =====================================================================
    # TOPIC 3: Database Design & Sharding
    # =====================================================================
    {
        "id": "db_001",
        "topic": "Database Design & Sharding",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What is database sharding?",
        "options": [
            "Replicating the same data across multiple database servers for read scalability",
            "Partitioning a large database into smaller, independent databases distributed across servers",
            "Normalizing tables to reduce data redundancy",
            "Creating database indexes to speed up queries",
        ],
        "correct": 1,
        "explanation": "Sharding (horizontal partitioning) splits a large database into smaller, independent shards, each stored on a separate server. Each shard holds a subset of the rows. This distributes load and enables horizontal scaling. The challenge is choosing a good shard key — a poor choice can lead to hotspots or make cross-shard queries expensive.",
        "hint": "Dividing one big database into many smaller ones, each on its own server.",
    },
    {
        "id": "db_002",
        "topic": "Database Design & Sharding",
        "difficulty": "medium",
        "type": "mcq",
        "question": "Which sharding strategy distributes data based on a hash of the shard key?",
        "options": [
            "Range-based sharding",
            "Directory-based sharding",
            "Hash-based sharding",
            "Geo-based sharding",
        ],
        "correct": 2,
        "explanation": "Hash-based sharding applies a hash function to the shard key and uses the hash value to determine which shard stores the row. This provides uniform distribution and avoids hotspots, but makes range queries across shards expensive because data is spread randomly. Re-sharding (changing the number of shards) also requires rehashing all data.",
        "hint": "The shard is determined by passing the key through a mathematical function.",
    },
    {
        "id": "db_003",
        "topic": "Database Design & Sharding",
        "difficulty": "hard",
        "type": "mcq",
        "question": "What is a common drawback of range-based sharding compared to hash-based sharding?",
        "options": [
            "Range-based sharding cannot be implemented in SQL databases",
            "Range-based sharding can create hotspots where some shards receive disproportionate load",
            "Range-based sharding requires more memory for the lookup table",
            "Range-based sharding only works with integer keys",
        ],
        "correct": 1,
        "explanation": "Range-based sharding divides data by key ranges (e.g., users A-M on shard 1, N-Z on shard 2). The problem is that data distribution is often uneven — for example, most users might have names starting with common letters, or active users might cluster in certain ranges. This creates hot shards while others sit idle. Hash-based sharding distributes more uniformly but sacrifices range query efficiency.",
        "hint": "What happens when 80% of your users have last names starting with the same few letters?",
    },
    {
        "id": "db_004",
        "topic": "Database Design & Sharding",
        "difficulty": "easy",
        "type": "mcq",
        "question": "What does denormalization sacrifice in exchange for better read performance?",
        "options": [
            "Data consistency",
            "Write performance and data redundancy",
            "Query flexibility",
            "Database security",
        ],
        "correct": 1,
        "explanation": "Denormalization adds redundant data (duplicating data across tables) to avoid expensive JOINs on reads. The trade-off is: writes become slower and more complex (multiple copies must be updated), storage increases due to redundancy, and there's a risk of data inconsistency if copies get out of sync. It's a common optimization in read-heavy systems.",
        "hint": "You're duplicating data to make reads faster — what does that cost you?",
    },
    {
        "id": "db_005",
        "topic": "Database Design & Sharding",
        "difficulty": "hard",
        "type": "open_ended",
        "question": "Design a sharding strategy for a global user database with 1 billion users. Users frequently interact with users in their own region (80% of traffic), but occasionally interact globally (20%). Consider shard key selection, data locality, and cross-shard operations.",
        "correct": None,
        "explanation": "A good approach: use geographic-region-based sharding as the primary shard key (e.g., NA, EU, APAC, SA). Each region has multiple shards using hash-based sub-sharding (hash(user_id) % num_shards_in_region). This keeps 80% of traffic within-region. For cross-region operations (the 20%), implement a fan-out query pattern that sends the request to all regions and aggregates results. Use a global user directory (e.g., DynamoDB or a separate index) mapping user_id → region. For read-heavy cross-region lookups, consider caching user profiles in a global CDN-tier cache. For writes, accept eventual consistency across regions using CRDTs or last-writer-wins conflict resolution. Re-sharding: use consistent hashing within each region to minimize data movement when adding shards.",
        "hint": "80% of traffic is local. How do you design for locality first without breaking the global 20%?",
    },

    # =====================================================================
    # TOPIC 4: Message Queues & Event-Driven Architecture
    # =====================================================================
    {
        "id": "mq_001",
        "topic": "Message Queues & Event-Driven Architecture",
        "difficulty": "easy",
        "type": "mcq",
        "question": "What is the primary benefit of introducing a message queue between a producer and a consumer service?",
        "options": [
            "It guarantees exactly-once delivery",
            "It decouples the producer from the consumer, allowing them to operate independently",
            "It reduces the total number of services needed",
            "It encrypts messages in transit",
        ],
        "correct": 1,
        "explanation": "A message queue decouples the producer (sender) from the consumer (receiver). The producer can publish messages without waiting for the consumer to be available, and the consumer can process messages at its own pace. This enables asynchronous processing, improves fault tolerance (messages persist in the queue if the consumer crashes), and allows independent scaling of producers and consumers.",
        "hint": "What problem does putting a buffer between the sender and receiver solve?",
    },
    {
        "id": "mq_002",
        "topic": "Message Queues & Event-Driven Architecture",
        "difficulty": "medium",
        "type": "mcq",
        "question": "In a messaging system, what does 'at-least-once delivery' guarantee?",
        "options": [
            "Every message is delivered exactly once and never duplicated",
            "Every message is delivered at least once, but may be duplicated",
            "Messages are delivered in the exact order they were sent",
            "Messages are delivered only if the consumer is actively listening",
        ],
        "correct": 1,
        "explanation": "At-least-once delivery guarantees that a message will not be lost — the consumer will receive it at least once. However, due to retries (e.g., after a consumer crash or network issue), the consumer might receive the same message multiple times. This means consumers must be idempotent (processing the same message twice has no side effects). It's the most common delivery guarantee in practice.",
        "hint": "The message won't get lost, but it might arrive more than once. What does this mean for the consumer?",
    },
    {
        "id": "mq_003",
        "topic": "Message Queues & Event-Driven Architecture",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What is the fundamental difference between a queue and a topic in messaging systems?",
        "options": [
            "A queue is faster than a topic",
            "A queue delivers each message to one consumer; a topic delivers each message to all subscribers",
            "A topic stores messages on disk; a queue stores them in memory",
            "A queue requires consumer acknowledgment; a topic does not",
        ],
        "correct": 1,
        "explanation": "In a queue (point-to-point model), each message is consumed by exactly one consumer from the competing consumer group. Once consumed, the message is removed. In a topic (publish-subscribe model), each message is delivered to all subscribers. Queues are used for task distribution (work queues); topics are used for event broadcasting (e.g., notify all services of a user signup event).",
        "hint": "One is 'whoever grabs it first'; the other is 'everyone gets a copy'.",
    },
    {
        "id": "mq_004",
        "topic": "Message Queues & Event-Driven Architecture",
        "difficulty": "hard",
        "type": "mcq",
        "question": "What problem does backpressure (or flow control) solve in a streaming system?",
        "options": [
            "Network congestion between data centers",
            "A fast producer overwhelming a slow consumer, causing memory exhaustion or dropped data",
            "Serialization overhead when messages are large",
            "Leader election in a partitioned Kafka topic",
        ],
        "correct": 1,
        "explanation": "Backpressure prevents a fast producer from overwhelming a slow consumer. Without it, the consumer's input buffer grows indefinitely, leading to memory exhaustion, increased garbage collection pauses, and eventually out-of-memory errors. Solutions include: bounded buffers (block producer when full), reactive streams (consumer signals how much it can handle via request(n)), and drop policies (newest/oldest).",
        "hint": "What happens when data arrives faster than it can be processed?",
    },
    {
        "id": "mq_005",
        "topic": "Message Queues & Event-Driven Architecture",
        "difficulty": "hard",
        "type": "open_ended",
        "question": "Design an event-driven architecture for an e-commerce order processing system. When a customer places an order, the system must: validate inventory, process payment, update inventory, send confirmation email, and trigger shipping. Some steps can be parallel, some must be sequential. How would you orchestrate this?",
        "correct": None,
        "explanation": "A good design uses an event-driven saga pattern. The Order Service creates an order with 'pending' status and emits an 'OrderPlaced' event. Multiple services subscribe: Inventory Service validates stock and emits 'InventoryReserved' or 'InventoryFailed'; Payment Service processes payment and emits 'PaymentProcessed' or 'PaymentFailed'. A Saga Orchestrator (or choreography via events) coordinates: inventory and payment can run in parallel. If both succeed, emit 'OrderConfirmed' — this triggers Email Service (send confirmation) and Shipping Service (create shipment). If either fails, emit 'OrderFailed' and run compensating transactions: release inventory, void payment. Use Kafka/RabbitMQ with at-least-once delivery and idempotent handlers. Dead-letter queues handle poison messages. This design provides loose coupling, independent scaling, and fault isolation.",
        "hint": "Some steps can happen simultaneously, others must wait. How do you coordinate without a monolith?",
    },

    # =====================================================================
    # TOPIC 5: Microservices & API Design
    # =====================================================================
    {
        "id": "ms_001",
        "topic": "Microservices & API Design",
        "difficulty": "easy",
        "type": "mcq",
        "question": "What is the main trade-off when choosing microservices over a monolithic architecture?",
        "options": [
            "Microservices are simpler to develop but harder to deploy",
            "Microservices improve scalability and team autonomy at the cost of operational complexity",
            "Monoliths scale better but are harder to maintain",
            "Microservices always perform better than monoliths",
        ],
        "correct": 1,
        "explanation": "Microservices decompose the system into independently deployable services, each owning its own data and logic. This improves scalability (services scale independently), fault isolation, and team autonomy. The cost: operational complexity (service discovery, inter-service communication, distributed tracing), data consistency challenges, network latency, and debugging difficulty across service boundaries.",
        "hint": "You gain independence but lose simplicity. What's the price of decoupling?",
    },
    {
        "id": "ms_002",
        "topic": "Microservices & API Design",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What is the primary purpose of an API gateway in a microservices architecture?",
        "options": [
            "To provide a single entry point that handles routing, authentication, rate limiting, and protocol translation",
            "To serve as the database proxy for all microservices",
            "To compile multiple services into a single deployable unit",
            "To replace service-to-service direct communication",
        ],
        "correct": 0,
        "explanation": "An API gateway is a single entry point for all client requests. It routes requests to the appropriate backend service, handles cross-cutting concerns (authentication, rate limiting, logging), performs protocol translation (REST → gRPC), and can aggregate responses from multiple services. It simplifies the client's view of the system but adds a hop in the request path.",
        "hint": "A front door that handles security, directions, and translation before forwarding you to the right room.",
    },
    {
        "id": "ms_003",
        "topic": "Microservices & API Design",
        "difficulty": "medium",
        "type": "mcq",
        "question": "Which pattern is commonly used to maintain data consistency across microservices without distributed transactions?",
        "options": [
            "Two-Phase Commit (2PC)",
            "The Saga pattern with compensating transactions",
            "Database replication across services",
            "Shared database between services",
        ],
        "correct": 1,
        "explanation": "The Saga pattern coordinates a series of local transactions across services, where each step publishes an event that triggers the next step. If a step fails, compensating transactions undo the previous steps. Unlike distributed transactions (2PC), sagas don't hold locks and are suitable for long-running business processes. They offer eventual consistency instead of strong consistency.",
        "hint": "When a multi-step business process fails midway, how do you clean up without distributed transactions?",
    },
    {
        "id": "ms_004",
        "topic": "Microservices & API Design",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What does idempotency mean in the context of API design?",
        "options": [
            "The API returns the same response every time it is called",
            "Multiple identical requests have the same effect as a single request",
            "The API encrypts all requests and responses",
            "The API can handle multiple concurrent requests without locking",
        ],
        "correct": 1,
        "explanation": "Idempotency means that making the same request multiple times produces the same result as making it once (no additional side effects). This is critical for safe retries in distributed systems — if a client doesn't receive a response due to network failure, it can safely retry without risking duplicate side effects. PUT and DELETE are idempotent by HTTP spec; POST is not. Implement idempotency keys for non-idempotent operations.",
        "hint": "If the client sends the same request twice by accident, should the second one change anything?",
    },
    {
        "id": "ms_005",
        "topic": "Microservices & API Design",
        "difficulty": "hard",
        "type": "open_ended",
        "question": "Design a versioning strategy for a public REST API that serves 10,000+ developers. You need to support existing clients while evolving the API. Consider URL vs header versioning, deprecation, and migration.",
        "correct": None,
        "explanation": "A robust API versioning strategy: Use URL-based versioning (/v1/, /v2/) — it's explicit, cacheable, and easy to test. Support each version for a minimum of 12 months with a deprecation notice 6 months before removal. Include a Sunset header in deprecated versions pointing to migration docs. For intermediate changes within a version, additive-only changes (new fields, new endpoints) are backward-compatible. Breaking changes require a new version. Use a gateway to route to different service versions. Maintain an API changelog. For version transition: offer an upgrade endpoint that validates the client works with the new version. Use feature flags for gradual rollout. Monitor deprecated version usage and notify high-traffic clients personally.",
        "hint": "You can't force developers to upgrade overnight. How do you support both old and new simultaneously?",
    },

    # =====================================================================
    # TOPIC 6: CAP Theorem & Distributed Systems
    # =====================================================================
    {
        "id": "cap_001",
        "topic": "CAP Theorem & Distributed Systems",
        "difficulty": "easy",
        "type": "mcq",
        "question": "According to the CAP theorem, during a network partition, a distributed system must choose between:",
        "options": [
            "Latency and throughput",
            "Consistency and availability",
            "Security and performance",
            "Scalability and durability",
        ],
        "correct": 1,
        "explanation": "The CAP theorem states that a distributed system can provide at most two of three properties: Consistency (all nodes see the same data), Availability (every request gets a response), and Partition Tolerance (the system continues operating despite network failures). Since network partitions are inevitable in distributed systems, you must choose between Consistency (CP) or Availability (AP) during a partition.",
        "hint": "When the network breaks, you can't have both accuracy and uptime. Which do you sacrifice?",
    },
    {
        "id": "cap_002",
        "topic": "CAP Theorem & Distributed Systems",
        "difficulty": "medium",
        "type": "mcq",
        "question": "Which type of database is typically designed to favor Availability over Consistency (AP systems)?",
        "options": [
            "Relational databases like PostgreSQL",
            "Eventually-consistent NoSQL databases like Cassandra or DynamoDB",
            "In-memory databases like Redis",
            "Graph databases like Neo4j",
        ],
        "correct": 1,
        "explanation": "Cassandra and DynamoDB are AP systems — they prioritize availability and partition tolerance over strong consistency. During a network partition, they accept writes on both sides and reconcile differences later using techniques like last-writer-wins or vector clocks. They provide eventual consistency: given enough time without new updates, all replicas will converge to the same value.",
        "hint": "This database lets you write on both sides of a network break and figures out the truth later.",
    },
    {
        "id": "cap_003",
        "topic": "CAP Theorem & Distributed Systems",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What is the practical difference between strong consistency and eventual consistency for a user-facing application?",
        "options": [
            "Strong consistency always has lower latency than eventual consistency",
            "Strong consistency guarantees that a read always returns the most recent write; eventual consistency may return stale data temporarily",
            "Eventual consistency is only used in single-node databases",
            "Strong consistency cannot be implemented in distributed systems",
        ],
        "correct": 1,
        "explanation": "Strong consistency ensures that once a write is acknowledged, all subsequent reads will return that value. This provides a familiar programming model but requires coordination (slower writes, lower availability during partitions). Eventual consistency allows temporary staleness — a read might return an older value if the write hasn't propagated yet — but provides better availability and lower latency. Choose based on requirements: bank balances need strong consistency; social media likes can be eventually consistent.",
        "hint": "One says 'you always see the latest data'; the other says 'you'll see it eventually'.",
    },
    {
        "id": "cap_004",
        "topic": "CAP Theorem & Distributed Systems",
        "difficulty": "hard",
        "type": "mcq",
        "question": "What problem does the Paxos algorithm solve in distributed systems?",
        "options": [
            "Efficient data compression across nodes",
            "Reaching consensus among a set of unreliable nodes on a single value",
            "Load balancing requests across servers",
            "Encrypting data in transit between nodes",
        ],
        "correct": 1,
        "explanation": "Paxos is a consensus algorithm that allows a group of unreliable nodes to agree on a single value, even when some nodes fail or messages are lost. It's the foundation for many distributed systems: Google Chubby, Apache ZooKeeper, and etcd. A simpler alternative is Raft, which provides the same guarantees with a more understandable design. Consensus is essential for leader election, distributed locking, and maintaining a consistent replicated log.",
        "hint": "How do multiple machines agree on something when some of them might be lying or unreachable?",
    },
    {
        "id": "cap_005",
        "topic": "CAP Theorem & Distributed Systems",
        "difficulty": "hard",
        "type": "open_ended",
        "question": "You are designing a global distributed database for a social media platform. Users can post and like content. A user's 'like count' on a post must be eventually consistent within 5 seconds, but the content of a post must be strongly consistent. How would you architect this hybrid consistency model?",
        "correct": None,
        "explanation": "Use a hybrid approach: Store post content in a strongly consistent store (e.g., etcd or a single-leader database with quorum reads) — the content is write-once per post, so strong consistency is achievable and the coordination overhead is limited. Store like counts in an AP system (e.g., Cassandra, DynamoDB) with eventual consistency — likes are commutative, conflict-free operations that tolerate eventual consistency well. Use CRDTs (Conflict-Free Replicated Data Types) for the like counter to prevent conflicts. Read path: fetch post content from the strong store, like count from the AP store. For the 5-second bound, use a local cache with TTL or read-repair. For analytics, a separate streaming pipeline (Kafka → Flink) can process all like events for real-time leaderboards. This design maximizes availability where possible and applies consistency only where necessary.",
        "hint": "Not all data needs the same guarantees. How do you give each type of data what it needs?",
    },

    # =====================================================================
    # TOPIC 7: Performance & Reliability
    # =====================================================================
    {
        "id": "perf_001",
        "topic": "Performance & Reliability",
        "difficulty": "easy",
        "type": "mcq",
        "question": "What is the difference between throughput and latency?",
        "options": [
            "Throughput measures data transfer rate; latency measures delay. They are inversely related under constant concurrency",
            "Throughput and latency are the same thing measured in different units",
            "Latency measures total capacity; throughput measures response time",
            "Throughput is network-specific; latency is application-specific",
        ],
        "correct": 0,
        "explanation": "Throughput is the rate at which a system processes work (requests/second, bytes/second). Latency is the time delay for a single operation to complete. Under Little's Law: Concurrency = Throughput × Latency. For a fixed concurrency, optimizing for reduced latency doesn't always increase throughput, and increasing throughput can increase latency if the system saturates. Both must be measured and optimized together.",
        "hint": "One is 'how many per second', the other is 'how long does one take'.",
    },
    {
        "id": "perf_002",
        "topic": "Performance & Reliability",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What does a circuit breaker pattern prevent in a distributed system?",
        "options": [
            "SQL injection attacks",
            "Cascading failures by stopping calls to a failing service and failing fast",
            "Data loss during network partitions",
            "Unauthorized access to APIs",
        ],
        "correct": 1,
        "explanation": "The circuit breaker pattern prevents cascading failures. When a downstream service starts failing (timeouts, errors), the circuit breaker 'opens' and subsequent calls fail immediately without reaching the failing service. This prevents resource exhaustion (threads waiting, connections pooling up) from propagating through the system. After a timeout, the circuit transitions to 'half-open' to test if the service has recovered. It's a critical resilience pattern in microservices.",
        "hint": "When one service is sick, this pattern stops other services from calling it and getting sick too.",
    },
    {
        "id": "perf_003",
        "topic": "Performance & Reliability",
        "difficulty": "medium",
        "type": "mcq",
        "question": "What is the primary purpose of a rate limiter in a web API?",
        "options": [
            "To encrypt all API traffic",
            "To control the number of requests a client can make within a time window, preventing abuse and ensuring fair usage",
            "To optimize database query performance",
            "To compress API responses for faster transmission",
        ],
        "correct": 1,
        "explanation": "A rate limiter controls how many requests a client can make in a given time window (e.g., 100 requests/minute). It prevents: abuse (DDoS, brute force), resource starvation by noisy neighbors, and cost overruns. Common algorithms: Token Bucket (bursty but bounded), Leaky Bucket (smooths traffic), Sliding Window (more accurate than fixed window). Rate limiters return 429 Too Many Requests with Retry-After headers.",
        "hint": "How do you stop one user from using all the resources and starving everyone else?",
    },
    {
        "id": "perf_004",
        "topic": "Performance & Reliability",
        "difficulty": "hard",
        "type": "mcq",
        "question": "What is 'tail latency' and why is it important for large-scale distributed systems?",
        "options": [
            "The latency of the slowest component in a critical path; it determines the overall user-perceived latency at scale",
            "The average latency measured at the end of a business day",
            "The latency introduced by tail-based load balancing algorithms",
            "The latency of the last request in a batch",
        ],
        "correct": 0,
        "explanation": "Tail latency refers to the slowest responses in a distribution (e.g., p99.9 latency — the requests that take longer than 99.9% of all requests). In large-scale systems, a single user request often fans out to hundreds or thousands of microservices (e.g., fetching a feed page). If each service has p99.9 latency of 50ms, the overall p99.9 latency becomes 50ms × fan-out, potentially seconds. This is why systems employ techniques like: hedging (send redundant requests to multiple replicas, use the first response), request hedging with speculative execution, and timeout decomposition.",
        "hint": "When your fan-out is 1000 services, the one slowest service determines how fast your user sees a response.",
    },
    {
        "id": "perf_005",
        "topic": "Performance & Reliability",
        "difficulty": "medium",
        "type": "open_ended",
        "question": "You are debugging a production issue: a service's p99 latency suddenly spiked from 50ms to 5 seconds. The CPU, memory, and network look normal. Walk through your debugging approach.",
        "correct": None,
        "explanation": "A systematic debugging approach: 1) Check if this is a genuine increase or a measurement artifact (monitoring pipeline issues, clock skew). 2) Correlate the spike with recent deployments, config changes, or traffic pattern shifts. 3) Look for lock contention — thread dumps or async profiles can show blocked threads. 4) Check downstream service latencies — the issue might be in a dependency (database query degradation, external API slowdown). 5) Investigate garbage collection logs — long GC pauses can spike latency without high CPU. 6) Check for resource contention at the OS level (page faults, swap, network packet loss). 7) Use distributed tracing to identify which service/operation contributes the most to the p99. 8) Check for throttling or rate limiting kicking in (the service itself being rate-limited by a downstream). 9) Investigate queue buildup — if requests are waiting in a queue before processing, that adds to latency. 10) Look for slow DNS lookups or TLS negotiation issues.",
        "hint": "100x latency spike but normal CPU/memory — the bottleneck is likely not compute. What else could it be?",
    },
]
